### PR TITLE
Email: Add Infomaniak

### PR DESCRIPTION
**Pull request by herver**
Their "ik.me" offering is free, privacy friendly and can be upgraded if needed

### CODE REVIEW

**Comment by herver** [comment]
I just noticed that the free offering (`ik.me`) is reserved for people living in Switzerland, the rest of their products is available for everyone though...

Maybe I should edit the link to point to the standard product page ?

**Comment by kakawait** [comment]
Yes, I'm not sure I'd like to add some services that is limited by choice to only one country.

But if you remove email from link, infomaniak can't be listed on email section no? And other services are open to other people outside Switzerland?

**Comment by herver** [comment]
The thing is that they do have a lot of offerings (IaaS, PaaS, Email, Housing) so I don't know if I should list them in each category.

Concerning the availability of services: they're all available to everyone (except the free email offering which is swiss resident only).

**Comment by kakawait** [comment]
Thus I think we should add to the most common denominator (or lowest level) aka IaaS? What do you think about?

**Pull request merged**
